### PR TITLE
Use a context manager

### PR DESCRIPTION
**Pull request by gforcada**
To read a file.

### CODE REVIEW

**Comment by gforcada** [comment]
@avoinea might you have a few minutes to review this? 😄

**Comment by gforcada** [comment]
@avoinea ping! 😊 are you still using it, should we transfer it to the `collective` GitHub org? 🤔 I would certainly love to have it integrated in `plone/meta` probably as a `pre-commit` hook 🎉

**Review by avoinea — APPROVED** [review]

**Comment by avoinea** [comment]
@gforcada I think we forked this repo from somewhere else, and now the owner removed it and this became the main repo. We should ping @gotcha or https://pypi.org/user/ree/ to give Plone Foundation rights on https://pypi.org/project/zptlint/

**Comment by gotcha** [comment]
@gforcada @avoinea 

I invited the `plone` user on pypi.

**Pull request merged**
